### ISSUE TITLE
介意我把你的repo扩充到支援小米网关吗

### ISSUE THREAD

**Issue by moshiba** [polunzh/homebridge-zigbee#1]
覺得要是能把小米的感應器也整合進homekit應該會是一件很好玩的事情

附上個可能的[驅動程式參考](https://github.com/TedTolboom/com.xiaomi-mi-zigbee)（尚未細看）

**Comment by polunzh** [comment]
@HsuanTingLu 抱歉，回复晚了。
这个repo没有任何使用限制。

**Comment by moshiba** [comment]
謝謝
那我改天再發個 pr
